[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NEXT_PUBLIC_TINA_CLIENT_ID = "a7f121a6-ef75-447d-bd19-ea1b25d3d4e2"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
